### ISSUE TITLE
Remover pluralização automática

### ISSUE THREAD

**Issue by leojgo** [biancaforbeci/SistemaPizzaria#9]

**Comment by biancaforbeci** [comment]
O que seria pluralização automática ?

**Comment by leojgo** [comment]
A plurarização do Entity Framework é em inglês, por isso o nome das tabelas estão desse jeito
![pluralizacao](https://user-images.githubusercontent.com/3331716/39090635-e802065c-45ba-11e8-8743-d17790dce1ae.JPG)

para remover, basta adicionar isso no MeuContexto.cs:

`protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();            
        }`
